config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  get "/about-us", to: "pages#about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :dogs, only: [:create, :new, :edit, :update, :destroy]

  get "users/:id", to: "profiles#show", as: :show_profile

  resources :matches, only: [:update, :show] do
    collection do
      get :my_matches
    end


    resources :messages, only: :create
    resources :doggy_dates, exclude: [:index, :destroy]
  end

  resources :doggy_dates, only: [:index, :destroy]
  resources :notifications, only: [] do
    collection do
      patch :mark_as_read
    end
  end

  get "matches", to: "profiles#matches", as: :matches
  get "settings", to: "profiles#settings", as: :settings
  resources :matches, only: %i[update]
  post "matches", to: "matches#create", as: :create_match

  # TODO: nest doggy_dates index, new and create actions under matches

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end


# for Profiles controller
# def index
#   @users = User.all
#   if params[:min_age] && params[:max_age]
#   @users = @users.where(params[:max_age].to_i, params[:min_age].to_i)
#   end
# end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def matches
    # Determining location of current user.
    # result = request.location
    # current_user.address = result.address
    # current_user.latitude = result.coordinates[0]
    # current_user.longitude = result.coordinates[1]
    # People who have accepted us, match exists:
    matches = Match.where(matchee_id: current_user.id)
    prematches = matches.where(status: "pending")
    # There is no match yet, make one thats not yet saved:
    users_matched = []
    matches1 = Match.where(matchee_id: current_user.id)
    # && Match.where(match.matcher.nearbys(10))
    matches1.each do |match|
      users_matched << match.matcher
    end
    matches2 = Match.where(matcher_id: current_user.id)
    matches2.each do |match|
      users_matched << match.matchee
    end
    users_matched << current_user
    users = User.all
    users_not_matched = users.select do |user|
      users_matched.exclude?(user) && !user.dogs.empty? # ONLY USERS WITH DOGS CAN MATCH
    end
    potential_matches = users_not_matched.map do |user|
      Match.new(matcher_id: current_user.id, matchee_id: user.id)
    end
    # Mix the two arrays together
    full_matches = (prematches + potential_matches)
    # @matches = Match.where(Match.first.matchee.dogs.first.gender == params[:gender])
    # @matches = Match.where(matchee.dogs.first.gender == params[:gender])
    # @matches = full_matches.matchee.dogs.where(gender: params[:gender])

    # match.matcher.dogs.first.gender == params[:gender] || match.matcher.dogs.first.gender == params[:gender].capitalize
    @matches = []
    full_matches.each do |match|
      matched_dogs = match.matcher == current_user ? match.matchee.dogs :  match.matcher.dogs
      matched_dogs = matched_dogs.where(size: params[:size]) if params[:size]
      matched_dogs = matched_dogs.where(gender: params[:gender]) if params[:gender]
      @matches << match if matched_dogs.present?

      # if match.matcher == current_user



      #   @matches << match
      #   else matched_dogs = match.matchee.dogs.where(size: params[:size]).where(gender: params[:gender])
      #   @matches << match if !matched_dogs.empty?
      #   elsif match.matchee == current_user
      #   matched_dogs = match.matcher.dogs.where(size: params[:size]).where(gender: params[:gender])
      #   # if match.matcher.dogs.any? { |dog| dog.gender.downcase == params[:gender] } &&
      #   # # match.matcher.dogs.any? { |dog| dog.age == params[:age] } &&
      #   # match.matcher.dogs.any? { |dog| dog.size == params[:size] }
      #   # @matches << match
      #   # end
      #   # match.matcher.dogs.any? { |dog| dog.personality == params[:personality] }
      #   # else match.matcher == current_user
      #   #     match.matchee.dogs.any? { |dog| dog.gender.downcase == params[:gender] } &&
      #   #     #   match.matchee.dogs.any? { |dog| dog.age == params[:age] } &&
      #   #       match.matchee.dogs.any? { |dog| dog.size == params[:size] }
      #   #     #   match.matchee.dogs.any? { |dog| dog.personality == params[:personality] }
      # end
    end

    # @matches = full_matches.select do |match|
    #  true

      # match.matcher.dogs.first.gender == params[:gender]
      # || match.matcher.dogs.first.gender == params[:gender].capitalize
      # match.matcher.dogs.first.gender == params[:gender] || match.matcher.dogs.first.gender == params[:gender].capitalize

      # match.matchee.dogs.first.where(gender: params[:gender]).nil?
      # full_matches.first.matchee.dogs.first.gender
   # end


  end

  # def filtered_by_gender
  # end

  # def dogs_by_preferences
  #   @dogs = Dog.where(nil)
  #   @dogs = @dogs.filter_by_location(params[:location]) if params[:location].present?
  #   @dogs = @dogs.filter_by_age(params[:age]) if params[:age].present?
  #   @dogs = @dogs.filter_by_gender(params[:gender]) if params[:gender].present?
  #   @dogs = @dogs.filter_by_size(params[:size]) if params[:size].present?
  #   @dogs = @dogs.filter_by_personality(params[:personailty]) if params[:personality].present?
  # end

  private

  def filtering_params(params)
    params.slice(:location, :gender, :age, :size, :personality)
  end
end

app/views/profiles/matches.html.erb
<div class="container mb-5  pt-3">
  <div class="d-flex" style="justify-content: space-between;">
  <h1 style="margin-left: 28%;">Find a Match</h1>

  <%# Can only start swiping if has dog %>
    <%= link_to settings_path do %>
      <button class="btn btn-primary">
          <%= image_tag("cog.svg", width: "22px") %>
      </button>
    <% end %>
  </div>
  <% if current_user.dogs.empty? %>
    <p><strong>Add your dog(s) to your <%= link_to "profile", show_profile_path(current_user.id) %> before you look for matches!</strong></p>
  <% else %>
    <%# Shows pending matches %>
    <%= turbo_stream_from "user_#{current_user.id}_pending_matches" %>
    <div id="pending_matches">
      <%= turbo_frame_tag 'tinder' do %>
        <div class="tinder">
          <div class="tinder--status">
            <i class="fa fa-remove"></i>
            <i class="fa fa-heart"></i>
          </div>
          <div class="tinder--cards">
            <% @matches.each do |match| %>
              <!-- card -->
              <%= render match %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<%# TODO Anna add filters button here %>

app/views/profiles/settings.html.erb
<div class="d-flex flex-column m-3" style="height: 100vh;">
  <div class="d-inline-flex p-2 justify-content-center">
    <h1>Doggy Preferences</h1>
  </div>
  <div class="d-inline-flex p-2">
    <form action="/matches" method="get" data-turbo="false">
    <label for="distance" class="form-label"><h5>Distance from me (km)</h5></label>
    <br>
    <input id="distance" type="range" value="10" min="1" max="20" step="1" oninput="this.nextElementSibling.value = this.value">
    <output>10</output>
  </div>
  <div class="d-flex flex-column p-2 mb-2">
    <h5>Gender</h5>
      <div class="d-inline-flex">
        <input class="settings-button" id="gender_female" name="gender[]" type="checkbox" value="female" />
        <label for="gender_female">Female</label>
        <input class="settings-button" id="gender_male" name="gender[]" type="checkbox" value="male" />
        <label for="gender_male">Male</label>
      </div>
  </div>
  <div class="d-flex flex-column p-2 mb-2">
    <h5>Size</h5>
      <div class="d-inline-flex">
        <input class="settings-button" id="size_small" name="size[]" type="checkbox" value="small" />
        <label for="size_small">Small</label>
        <input class="settings-button" id="size_medium" name="size[]" type="checkbox" value="medium" />
        <label for="size_medium">Medium</label>
        <input class="settings-button" id="size_large" name="size[]" type="checkbox" value="large" />
        <label for="size_large">Large</label>
      </div>
  </div>
  <div class="d-flex flex-inline justify-content-center">
    <input class="btn btn-submit" type="submit" value="Submit">
    <%= submit_tag "Reset", :class => "inputsubmit", :type => "reset" %>
  </div>
  </form>
</div>

app/views/profiles/show.html.erb
<div class="container pb-5 pt-3 mb-5" style="height:100vh;">
  <h1 class="text-center fw-semibold text-dark">
    <% @user.dogs.each do |dog| %>
      <% if dog == @user.dogs.first %>
        <%= "#{dog.name.capitalize} " %>
      <% else %>
        <%= "+ #{dog.name.capitalize}" %>
      <% end %>
    <% end %>
    <small class="fw-light fst-italic"> owned by <%= @user.first_name %></small>
  </h1>
  <p class="text-center"><strong>Overview:</strong> <%= @user.overview %></p>
  <%# Dog Tabs %>
  <ul class="nav nav-tabs" id="myTab" role="tablist">
  <% @user.dogs.each_with_index do |dog, index| %>
    <li class="nav-item" role="presentation">
      <button class="<%= index == 0 ? "nav-link active" : "nav-link" %>" id="tab-<%=index%>" data-bs-toggle="tab" data-bs-target="#tab-<%=index%>-pane" type="button" role="tab" aria-controls="tab-<%=index%>-pane" aria-selected="<%= index == 0 ? "true" : "false" %>"><%= dog.name.capitalize %></button>
    </li>
  <% end %>
  </ul>
  <%# Dog Tabs Content %>
  <div class="tab-content mb-2 pb-2" id="myTabContent">
  <% @user.dogs.each_with_index do |dog, index| %>
    <div class="<%= index == 0 ? "tab-pane fade show active" : "tab-pane fade" %>" id="tab-<%=index%>-pane" role="tabpanel" aria-labelledby="tab-<%=index%>" tabindex="0">
      <%# Dog Image Carousel %>
      <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <% if dog.photos.attached? %>
            <% dog.photos.each_with_index do |photo, index| %>
              <div class="<%= index == 0 ? "carousel-item active" : "carousel-item" %>">
                <%= cl_image_tag photo.key, class: "d-block w-100", height: 400, width: 400, crop: :fill %>
              </div>
            <% end %>
          <% else %>
            <div class="carousel-item active">
              <%= image_tag "dog.png", class: "d-block w-100"%>
            </div>
          <% end %>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
      <%# Dog Details %>
      <div class="row p-2 m-0" style="background-color: white;">
        <div class="col">
          <h3 class="py-1" ><%= dog.name.capitalize %>, <%= dog.age %>
          <% if dog.gender.downcase == "female" %>
            <iconify-icon icon="material-symbols:female"></iconify-icon>
          <% else %>
            <iconify-icon icon="material-symbols:male"></iconify-icon>
          <% end %>
          </h3>
          <p><iconify-icon icon="ph:ruler"></iconify-icon> <%= dog.size.capitalize %></p>
          <p><iconify-icon icon="fa-solid:dog"></iconify-icon> <%= dog.breed.capitalize %></p>
        </div>
        <div class="col d-flex justify-content-center align-items-center flex-wrap">
          <% if dog.personality %>
            <% dog.personality.each do |trait| %>
              <% if trait != "" %>
                <p class="btn btn-light m-1"><i><%= trait %></i></p>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
      <% if @user == current_user %>
      <div class="d-flex pb-3 justify-content-center"  style="background-color:white;">
        <button type="button" class="btn btn-primary text-white mx-1"><%= link_to "Edit #{dog.name.split.first.capitalize}", edit_dog_path(dog), class: "text-decoration-none text-reset" %></button>
        <button type="button" class="btn btn-primary text-white mx-1"><%= link_to "Delete #{dog.name.split.first.capitalize}",
                    dog_path(dog),
                    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
                    class: "text-decoration-none text-reset"
        %></button>
      </div>
      <% end %>
    </div>
  <% end %>
  </div>
  <%# Owner Details %>
  <div class="p-2" style="background-color: white;">
    <div class="d-flex justify-content-center align-items-center">
      <% if @user.photo.attached? %>
        <%= cl_image_tag(@user.photo.key, :transformation=>[{:gravity=>"face", :height=>400, :width=>400, :crop=>"crop"}, {:radius=>"max"}, {:width=>70, :crop=>"scale"}]) %>
      <% else %>
        <%= image_tag "person.png", width: 70, class: "rounded-circle" %>
      <% end %>
      <h3 class="ps-3"><%= @user.first_name.capitalize %>, <%= @user.age %>
      <% if @user.gender.downcase == "female" %>
        <iconify-icon icon="material-symbols:female"></iconify-icon>
      <% else %>
        <iconify-icon icon="material-symbols:male"></iconify-icon>
      <% end %>
      </h3>
    </div>
    <% if @user == current_user %>
    <div class="d-flex justify-content-center mt-2">
      <button type="button" class="btn btn-primary text-white mx-1"><%= link_to "Update your profile", edit_user_registration_path, class: "text-decoration-none text-reset" %></button>
      <button type="button" class="btn btn-primary text-white mx-1"><%= link_to "Add a dog", new_dog_path, class: "text-decoration-none text-reset" %></button>
    </div>
    <% end %>
    <div class="d-flex justify-content-center mt-2">
      <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" do %>
        <button class="btn btn-submit text-white mx-1">Dog Out
          <%= image_tag("logout.svg") %>
        </button>
      <% end %>
    </div>
</div>