config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  get "/about-us", to: "pages#about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :dogs, only: [:create, :new, :edit, :update, :destroy]

  get "users/:id", to: "profiles#show", as: :show_profile

  resources :matches, only: [:update, :show] do
    collection do
      get :my_matches
    end


    resources :messages, only: :create
    resources :doggy_dates, exclude: [:index, :destroy]
  end

  resources :doggy_dates, only: [:index, :destroy]
  resources :notifications, only: [] do
    collection do
      patch :mark_as_read
    end
  end

  get "matches", to: "profiles#matches", as: :matches
  get "settings", to: "profiles#settings", as: :settings
  resources :matches, only: %i[update]
  post "matches", to: "matches#create", as: :create_match

  # TODO: nest doggy_dates index, new and create actions under matches

end

app/models/match.rb
class Match < ApplicationRecord
  enum :status, { pending: 0, declined: 1, accepted: 2 }
  belongs_to :matcher, class_name: "User", foreign_key: 'matcher_id'
  belongs_to :matchee, class_name: "User", foreign_key: 'matchee_id'
  has_many :messages, dependent: :destroy
  has_many :doggy_dates, dependent: :destroy
  has_many :dogs, through: :matcher

  validates_uniqueness_of :matchee_id, { scope: :matcher_id }
  validates :matchee_id, comparison: { other_than: :matcher_id }

  # For create, currrent_user is matcher
  after_create_commit -> { broadcast_prepend_to "user_#{matchee.id}_pending_matches", partial: "matches/match", locals: { match: self }, target: "pending_matches" }
  # after_create_commit -> { broadcast_remove_to "user_#{matcher.id}_pending_matches" }

  # For update, currrent_user is matchee
  after_update_commit -> { broadcast_remove_to "user_#{matchee.id}_pending_matches" }
  # after_update_commit -> { broadcast_prepend_to "user_#{matcher.id}_pending_matches", partial: "matches/match", locals: { match: self }, target: "pending_matches" }

  # after_update_commit -> { broadcast_prepend_to "user_#{matchee.id}_pending_matches", partial: "matches/match", locals: { match: self }, target: "pending_matches" }
  # after_update_commit -> { broadcast_remove_to "user_#{matcher.id}_pending_matches" }
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def my_matches
    @matches1 = Match.where(matchee_id: current_user.id).where(status: 2)
    @matches2 = Match.where(matcher_id: current_user.id).where(status: 2)
  end

  def destroy
  end

  def show
    @match = Match.find(params[:id])
    @message = Message.new
  end

  def create
    match = Match.new(match_params)
    if match.save
      redirect_to matches_path(gender: params[:gender], size: params[:size])
    else
      redirect_to matches_path(gender: params[:gender], size: params[:size]), status: :unprocessable_entity, alert: "Try again later"
    end
  end

  def update
    # Save
    @match = Match.find(params[:id])
    if @match.update(match_params)
      # Create Notification (for both the other user & current_user)
      if params[:match][:status] == "accepted"
        Notification.create(recipient: @match.matcher, actor: current_user, action: "matched", notifiable: @match)
        Notification.create(recipient: @match.matchee, actor: current_user, action: "matched", notifiable: @match)
      end
      redirect_to matches_path(gender: params[:gender], size: params[:size]), status: :see_other
    else
      redirect_to matches_path(gender: params[:gender], size: params[:size]), status: :unprocessable_entity, alert: "Try again later"
    end
  end

  private

  def match_params
    params.require(:match).permit(:status, :matchee_id, :matcher_id)
  end

end

app/views/matches/_chat_cards.html.erb
<% @matches1.each do |match| %>
  <%=link_to match_path(match) do %>
  <div class="chat" style="margin-top:8px;">
    <div class="card__avatar">
      <%= cl_image_tag match.matcher.dogs.first.photos.first.key, height: 56, width: 56, crop: :fill%>
      <div class="badge"></div>
    </div>
    <div>
      <h3 class="title"><% match.matcher.dogs.each do |dog| %>
        <%="#{dog.name} "%>
        <% end %>
        <%="and #{match.matcher.first_name}"%>
      </h3>
      <% if match.messages.present? %>
        <p>
        <%= "You: " if match.messages.last.user == current_user %>
        <%=match.messages.last.content%>
        </p>
      <%else%>
        <p>Say Hello!</p>
      <%end %>
    </div>
  </div>
  <% end %>
<% end %>
<% @matches2.each do |match| %>
  <%=link_to match_path(match) do %>
    <div class="chat" style="margin-top:8px;">
      <div class="card__avatar">
        <%= cl_image_tag match.matchee.dogs.first.photos.first.key, height: 56, width: 56, crop: :fill%>
        <div class="badge"></div>
      </div>
      <div>
        <h3 class="title"><% match.matchee.dogs.each do |dog| %>
          <%="#{dog.name} "%>
          <% end %>
          <%="and #{match.matchee.first_name}"%>
        </h3>
        <% if match.messages.present? %>
          <p>
          <%= "You: " if match.messages.last.user == current_user %>
          <%=match.messages.last.content%>
          </p>
        <%else%>
          <p>Say Hello!</p>
        <%end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/matches/_match.html.erb
<%# <div class="tinder">
  <div class="tinder--status">
    <i class="fa fa-remove"></i>
    <i class="fa fa-heart"></i>
  </div> %>


      <% if match.persisted? %>
        <% match.matcher.dogs.each do |dog| %>
          <div class="tinder--card">
            <% if dog.photos.attached? %>
              <%= cl_image_tag dog.photos.first.key, height: 400, width: 400, crop: :fill %>
            <% else %>
            <%= image_tag "dog.png", width: 500 %>
            <% end %>
            <div class="text" style="margin-top: 0px; margin-left:0px; text-align: left; padding:10px; margin-left:10px;">
              <h2><%= link_to "#{dog.name.capitalize}, #{dog.age}", show_profile_path(match.matcher) %></h2>
            </div>
            <ul style="text-align:left; margin-left:10px; text-align:left; padding-left:0px; margin-left:20px;">
            <li style="list-style-type:none;"><iconify-icon icon="bi:gender-ambiguous"></iconify-icon><%=" #{dog.gender.capitalize}"%></li>
            <li style="list-style-type:none;"><iconify-icon icon="fa6-solid:dog"></iconify-icon><%=" #{dog.breed.capitalize}"%></li>
            </ul>
            <div class="tinder--buttons" style="display: flex; align-items: center; justify-content: center; margin-right: 30px;">
              <%= link_to match_path(match, match:{status: "declined" }, gender: params[:gender], size: params[:size]), id: 'nope', data: {turbo_method: "PATCH"} do %>
                <button><i class="fa fa-remove" style="padding:20px;"></i></button>
              <% end %>

              <%= link_to match_path(match, match:{ status: "accepted" }, gender: params[:gender], size: params[:size]), id: 'love', data: {turbo_method: "PATCH"} do %>
                <button><i class="fa fa-heart" style="padding:20px;"></i></button>
              <% end %>
            </div>
          </div>
        <% end %>
      <% else %>
        <% match.matchee.dogs.each do |dog| %>
          <div class="tinder--card">
            <% if dog.photos.attached? %>
              <%= cl_image_tag dog.photos.first.key, height: 400, width: 400, crop: :fill %>
            <% else %>
              <%= image_tag "dog.png", width: 500 %>
            <% end %>
            <div class="text" style="margin-top: 0px; margin-left:0px; text-align: left; padding:10px; margin-right: 30px; margin-left:10px;">
              <h2><%= link_to "#{dog.name.capitalize}, #{dog.age}", show_profile_path(match.matchee) %></h2>
            </div>
            <ul style="text-align:left; margin-left:10px; text-align:left; padding-left:0px; margin-left:20px;">
            <li style="list-style-type:none;"><iconify-icon icon="bi:gender-ambiguous"></iconify-icon><%="#{dog.gender.capitalize}"%></li>
            <li style="list-style-type:none;"><iconify-icon icon="fa6-solid:dog"></iconify-icon><%="#{dog.breed.capitalize}"%></li>
            </ul>
            <div class="tinder--buttons" style="display: flex; align-items: center; justify-content: center;">
              <%= link_to create_match_path(match, match:{status: "declined", id: 'nope', matchee_id: match.matchee_id, matcher_id: match.matcher_id}, gender: params[:gender], size: params[:size]), data: {turbo_method: "POST"} do %>
                <button><i class="fa fa-remove" style="padding:20px;"></i></button>
              <% end %>

              <%= link_to create_match_path(match, match:{status: "pending", id: 'love', matchee_id: match.matchee_id, matcher_id: match.matcher_id}, gender: params[:gender], size: params[:size]), data: {turbo_method: "POST"} do %>
                <button><i class="fa fa-heart" style="padding:20px;"></i></button>
              <% end %>
            </div>
          </div>
        <% end%>
      <% end %>

    <%# <div class="tinder--card">
      <img src="https://placeimg.com/600/300/animals">
      <h3>Demo card 2</h3>
      <p>This is a demo for Tinder like swipe cards</p>
    </div>
    <div class="tinder--card">
      <img src="https://placeimg.com/600/300/nature">
      <h3>Demo card 3</h3>
      <p>This is a demo for Tinder like swipe cards</p>
    </div>
    <div class="tinder--card">
      <img src="https://placeimg.com/600/300/tech">
      <h3>Demo card 4</h3>
      <p>This is a demo for Tinder like swipe cards</p>
    </div>
    <div class="tinder--card">
      <img src="https://placeimg.com/600/300/arch">
      <h3>Demo card 5</h3>
      <p>This is a demo for Tinder like swipe cards</p>
    </div> %>

app/views/matches/my_matches.html.erb
<div class="container  pt-3" style="margin-bottom:200px;">
  <%= turbo_stream_from dom_id(current_user, :matches) %>
  <h1 style="text-align:center;">Matches</h1>

    <div class="wrapper" style="margin-top: 16px; margin-bottom: 16px; padding-bottom: 10px;">
      <% @matches1.each do |match| %>
      <% match.matcher.dogs.each do |dog| %>
        <%=link_to match_path(match) do %>
        <div class="item" style="margin-right:15px; color:black; font-size: 18px;">
          <%=cl_image_tag dog.photos.first.key, height: 70, width: 70, crop: :fill%>
        <p><%=dog.name%></p>
        </div>
        <% end %>
      <% end %>
      <% end %>
      <% @matches2.each do |match| %>
      <% match.matchee.dogs.each do |dog| %>
      <%=link_to match_path(match) do %>
        <div class="item" style="margin-right:15px; color:black; font-size: 18px;">
          <%=cl_image_tag dog.photos.first.key, height: 70, width: 70, crop: :fill%>
        <p><%= dog.name%></p>
        </div>
        <% end %>
      <% end %>
      <% end %>
    </div>

    <%= render "matches/chat_cards"%>
</div>

app/views/matches/show.html.erb
<div style="position: fixed; height: 87vh; width: 100vw; top: 20; left: 0;">
  <div class="bg-white w-100 h-100 position-relative">
    <div class="container chatroom"
      data-controller="match-subscription"
      data-match-subscription-match-id-value="<%= @match.id %>"
      data-match-subscription-current-user-id-value="<%= current_user.id %>"

      style="height: 70%;  overflow: scroll; background-color:white;">

      <h1><%= @match.matcher == current_user ? (link_to "#{@match.matchee.first_name}", show_profile_path(@match.matchee)) : (link_to "#{@match.matcher.first_name}", show_profile_path(@match.matcher)) %></h1>
      <div class="content bootstrap snippets bootdey decor-default a-chat chat-body pb-5" style="outline: none;">
        <div class="messages" data-match-subscription-target="messages">
          <% @match.messages.each do |message| %>
            <% if message.doggy_date.present? && message.user_id == current_user.id %>
              <%= render "doggy_dates/inviter_form", message: message   %>
            <% elsif message.doggy_date.present? && message.user_id != current_user.id %>
              <%= render "doggy_dates/request_form", doggy_date: message.doggy_date, match: @match, message: message %>
            <% else %>
              <%= render "messages/message", message: message %>
            <% end %>
          <% end %>
        </div>
        <div class="answer-add"></div>
      </div>
      <div class="pb-4 bg-white position-absolute bottom-0 w-99" style="height: 220px;">
        <div class="d-flex">
          <div>
            <%= link_to "Doggy Date?", new_match_doggy_date_path(@match), class:"btn btn-primary flex-shrink-1 me-1", style: "width: 80px" %>
          </div>
          <div class="flex-grow-1">
            <%= simple_form_for [@match, @message],
              html: { data: { action: "turbo:submit-end->match-subscription#resetForm" }, class: "d-flex" } do |f|
            %>
            <%= f.input :content,
              label: false,
              placeholder: "Write a Message",
              wrapper_html: {class: "flex-grow-1"}
            %>
            <%= f.submit "Send", class: "btn btn-primary mb-3" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>