config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  get "/about-us", to: "pages#about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :dogs, only: [:create, :new, :edit, :update, :destroy]

  get "users/:id", to: "profiles#show", as: :show_profile

  resources :matches, only: [:update, :show] do
    collection do
      get :my_matches
    end


    resources :messages, only: :create
    resources :doggy_dates, exclude: [:index, :destroy]
  end

  resources :doggy_dates, only: [:index, :destroy]
  resources :notifications, only: [] do
    collection do
      patch :mark_as_read
    end
  end

  get "matches", to: "profiles#matches", as: :matches
  get "settings", to: "profiles#settings", as: :settings
  resources :matches, only: %i[update]
  post "matches", to: "matches#create", as: :create_match

  # TODO: nest doggy_dates index, new and create actions under matches

end

app/models/doggy_date.rb
class DoggyDate < ApplicationRecord
  enum :status, { pending: 0, declined: 1, accepted: 2 }
  belongs_to :message
  belongs_to :match
  validates :date, presence: true
end

app/controllers/doggy_dates_controller.rb
require 'http'
require 'google_search_results'
class DoggyDatesController < ApplicationController
  def index
    @doggy_dates = DoggyDate.all
    @pending_dates = @doggy_dates.select do |pending|
      pending.status == "pending" && current_user.doggy_dates
    end
    @accepted_dates = @doggy_dates.select do |accepted|
      accepted.status == "accepted" && current_user.doggy_dates
    end
  end

  def show
    @doggy_date = DoggyDate.find(params[:id])
  end

  def current_user?
    if current_user.id == pd.match.matcher_id
      "#{pd.match.matchee.first_name}"
    else
      "#{pd.match.matcher.first_name}"
    end
  end

  def new
    @match = Match.find(params[:match_id])
    @doggy_date = DoggyDate.new
    get_park = HTTP.get("https://api.mapbox.com/geocoding/v5/mapbox.places/dog&park.json?type=poi&proximity=#{current_user.longitude},#{current_user.latitude}&access_token=#{ENV['MAPBOX_API_KEY']}")
    get_park_parsed = JSON.parse(get_park)
    features = get_park_parsed["features"]
    # for loop needed in page to grab co-ordinates
    park_array = []
    for i in (1..5)
      park = features[i-1]
      address_name = park["place_name"]
      easy_name = park["text"]
      coord = park.dig "geometry", "coordinates"
      park = Park.create(
        address: address_name,
        name: easy_name,
        latitude: coord[1],
        longitude: coord[0]
      )
      # image = (image_scraper(park.address))
      # file = URI.open(image)
      # park.photo.attach(io: file, filename: "nes.png", content_type: "image/jpg")
      # park.save
      park_array << park
    end
    @markers = park_array.map do |dog_park|
      {
        lat: dog_park.latitude,
        lng: dog_park.longitude,
        info_window: render_to_string(partial: "info_window", locals: {dog_park: dog_park}),
        image_url: helpers.asset_url("green_paw.png")
        }
      end
  end

  def create
    @match = Match.find(params[:match_id])
    @message = @match.messages.build(content: "Let's go on a date", user: current_user)
    @doggydate = DoggyDate.new(doggy_date_params)
    @doggydate.message = @message
    @doggydate.match = @match
    if @match.save
      redirect_to match_path(@match)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    # Save
    @doggy_date = DoggyDate.find(params[:id])
    if @doggy_date.update(doggy_date_params)
      redirect_to root_path, status: :see_other
    else
      redirect_to match_path, status: :unprocessable_entity, alert: "Try again later"
    end
  end

  def destroy
    @doggydate = DoggyDate.find(params[:id])
    @doggydate.destroy
    # No need for app/views/restaurants/destroy.html.erb
    redirect_to doggy_dates_path, status: :see_other
  end

  private

  def image_scraper(address)
    criteria = {
      q: address,
      hl: "en",
      tbm: "isch",
      num: "1",
      ijn: "0",
      api_key: "541e3fb6cf756e3309b910c4456e0562d147645c9446a34160906134d66c0dcc"
    }
    search = GoogleSearch.new(criteria)
    result = search.get_hash[:images_results][0]
    result[:thumbnail]
  end

  def doggy_date_params
    params.require(:doggy_date).permit(:status, :location, :date)
  end
end

app/views/doggy_dates/_info_window.html.erb
<div>
  <%= image_tag "park_placeholder.jpeg", height: 75, width: 130 %>
  <strong><p><%=dog_park.name%></p></strong>
</div>

<%#cl_image_tag dog_park.photo.key%>

app/views/doggy_dates/_inviter_form.html.erb
<div>
  <div class="answer <%= message.user == current_user ? "right" : "left" %>" id="message-<%= message.id %>">
    <div class="avatar">
      <% if message.user.photo.attached? %>
        <%= cl_image_tag(message.user.photo.key, :transformation=>[{:gravity=>"face", :height=>400, :width=>400, :crop=>"crop"}, {:radius=>"max"}, {:width=>70, :crop=>"scale"}]) %>
      <% else %>
        <%= image_tag "person.png", width: 70, class: "rounded-circle"  %>
      <% end %>
    </div>
    <div class="name"><%= message.user.first_name %></div>
    <div class="text d-flex justify-content-left">
      <div>
        <h4 class='mt-2'>Invite Sent!</h4>
      </div>
    </div>
    <div class="time"><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></div>
  </div>
</div>

app/views/doggy_dates/_request_form.html.erb
<% if doggy_date.status == "pending" %>
  <div>
    <div class="answer <%= message.user == current_user ? "right" : "left" %>" id="message-<%= message.id %>">
      <div class="avatar">
        <% if message.user.photo.attached? %>
          <%= cl_image_tag(message.user.photo.key, :transformation=>[{:gravity=>"face", :height=>400, :width=>400, :crop=>"crop"}, {:radius=>"max"}, {:width=>70, :crop=>"scale"}]) %>
        <% else %>
          <%= image_tag "person.png", width: 70, class: "rounded-circle"  %>
        <% end %>
      </div>
      <div class="name"><%= message.user.first_name %></div>
      <div>
        <div>
          <div class="card doggy" style="margin: 0 auto; margin-bottom:20px; border-radius: 20px; opacity: 0.9;">
            <div class="row">
              <div class="card-body col-9">
                <h5 class="card-title" style="margin-left: 12px;">
                <%if current_user.id == doggy_date.match.matcher_id %>
                  <iconify-icon icon="fa-solid:dog"></iconify-icon> <%= "#{doggy_date.match.matchee.first_name}" %>
                <% else %>
                  <iconify-icon icon="fa-solid:dog"></iconify-icon> <%= "#{doggy_date.match.matcher.first_name}" %>
                <% end %></h5>
                <h5 class="card-subtitle mb-2" style="margin-left: 12px;">
                  <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-calendar-time" width="26" height="26" viewBox="0 0 24 24" stroke-width="1.2" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round" style="margin-top:7px;  vertical-align:bottom; padding-right: 5px;">
                  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                  <path d="M11.795 21h-6.795a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v4" />
                  <circle cx="18" cy="18" r="4" />
                  <path d="M15 3v4" />
                  <path d="M7 3v4" />
                  <path d="M3 11h16" />
                  <path d="M18 16.496v1.504l1 1" />
                  <% str_fmt = "%s-%s-%s" %>
                  <% str = doggy_date.date.split("T")[0] %>
                </svg><%= "#{str_fmt % [str[8,2], str[5,2], str[0,4]]}, #{doggy_date.date.split("T")[1]}" %></h5>
                <h5 class="card-text" style="margin-left: 12px; padding-right: 5px;"><iconify-icon icon="material-symbols:park" style="margin-right:5px;"></iconify-icon><%= "#{doggy_date.location}" %></h5>
              </div>
              <div class="card-body col-3">

                  <div class="card-link" style="position: absolute; right: 7px;top: 7px; color:black;"><iconify-icon icon="oi:question-mark" width="24"></iconify-icon></div>
              </div>
            </div>
            <div class="d-inline-flex justify-content-around" >
              <p><%= link_to "Accept?", match_doggy_date_path(match, message.doggy_date, doggy_date:{ status: "accepted" }), data: {turbo_method: "PATCH"}, class: "btn btn-light mr-2"%></p>
              <p><%= link_to "Decline?", match_doggy_date_path(match, message.doggy_date, doggy_date:{ status: "declined" }), data: {turbo_method: "PATCH"}, class: "btn btn-light ml-2" %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<% elsif doggy_date.status == "accepted" %>
  <div>
      <div class="answer <%= message.user == current_user ? "right" : "left" %>" id="message-<%= message.id %>">
        <div class="avatar">
          <% if message.user.photo.attached? %>
            <%= cl_image_tag(message.user.photo.key, :transformation=>[{:gravity=>"face", :height=>400, :width=>400, :crop=>"crop"}, {:radius=>"max"}, {:width=>70, :crop=>"scale"}]) %>
          <% else %>
            <%= image_tag "person.png", width: 70, class: "rounded-circle"  %>
          <% end %>
        </div>
        <div class="name"><%= message.user.first_name %></div>
        <div>
          <div>
            <div class="card doggy" style="margin: 0 auto; margin-bottom:20px; border-radius: 20px; opacity: 0.9; box-shadow: 2px 1px 1px 1px black;">
              <div class="row">
                <div class="card-body col-9">
                  <h5 class="card-title" style="margin-left: 12px;">
                  <%if current_user.id == doggy_date.match.matcher_id %>
                    <iconify-icon icon="fa-solid:dog"></iconify-icon> <%= "#{doggy_date.match.matchee.first_name}" %>
                  <% else %>
                    <iconify-icon icon="fa-solid:dog"></iconify-icon> <%= "#{doggy_date.match.matcher.first_name}" %>
                  <% end %></h5>
                  <h5 class="card-subtitle mb-2" style="margin-left: 12px;">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-calendar-time" width="26" height="26" viewBox="0 0 24 24" stroke-width="1.2" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round" style="margin-top:7px;  vertical-align:bottom; padding-right: 5px;">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                    <path d="M11.795 21h-6.795a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v4" />
                    <circle cx="18" cy="18" r="4" />
                    <path d="M15 3v4" />
                    <path d="M7 3v4" />
                    <path d="M3 11h16" />
                    <path d="M18 16.496v1.504l1 1" />
                    <% str_fmt = "%s-%s-%s" %>
                    <% str = doggy_date.date.split("T")[0] %>
                  </svg><%= "#{str_fmt % [str[8,2], str[5,2], str[0,4]]}, #{doggy_date.date.split("T")[1]}" %></h5>
                  <h5 class="card-text" style="margin-left: 12px; padding-right: 5px;"><iconify-icon icon="material-symbols:park" style="margin-right:5px;"></iconify-icon><%= "#{doggy_date.location}" %></h5>
                </div>
                <div class="card-body col-3">

                    <div class="card-link" style="position: absolute; right: 7px;top: 7px; color:black;"><iconify-icon icon="oi:question-mark" width="32"></iconify-icon></div>
                    <%= link_to doggy_date_path(doggy_date), data: {turbo_method: :delete} do %>
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6" style="height:30px; position:absolute; right: 9px; bottom: 9px; color: black;">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                      </svg>
                    <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="time"><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></div>
    </div>
  </div>
<% else %>
  <div>
    <div class="answer <%= message.user == current_user ? "right" : "left" %>" id="message-<%= message.id %>">
      <div class="avatar">
        <% if message.user.photo.attached? %>
          <%= cl_image_tag(message.user.photo.key, :transformation=>[{:gravity=>"face", :height=>400, :width=>400, :crop=>"crop"}, {:radius=>"max"}, {:width=>70, :crop=>"scale"}]) %>
        <% else %>
          <%= image_tag "person.png", width: 70, class: "rounded-circle"  %>
        <% end %>
      </div>
      <div class="name"><%= message.user.first_name %></div>
      <div class="text">
        <%= "DOGGYDATE DENIED" %>
      </div>
      <div class="time"><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></div>
    </div>
  </div>
<% end %>

app/views/doggy_dates/edit.html.erb
<h1>DoggyDates#edit</h1>
<p>Find me in app/views/doggy_dates/edit.html.erb</p>

app/views/doggy_dates/index.html.erb
<%# <h1>Doggy Dates</h1> %>
<div class="container pt-3" style="height: 100vh">
<h1>Doggy Dates</h1>
  <% @pending_dates.each do |pd| %>
    <div class="card doggy" style="margin: 0 auto; margin-bottom:20px; border-radius: 20px; opacity: 0.9; box-shadow: 2px 1px 1px 1px black; color:black;">
      <div class="row" style="color:black;">
        <div class="card-body col-9" style="color:black;">
          <h5 class="card-title" style="margin-left: 12px; color:black;">
          <%if current_user.id == pd.match.matcher_id %>
            <iconify-icon icon="fa-solid:dog"></iconify-icon> <%= "#{pd.match.matchee.first_name}" %>
          <% else %>
            <iconify-icon icon="fa-solid:dog"></iconify-icon> <%= "#{pd.match.matcher.first_name}" %>
          <% end %></h5>
          <h5 class="card-subtitle mb-2" style="margin-left: 12px; color:black;">
            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-calendar-time" width="26" height="26" viewBox="0 0 24 24" stroke-width="1.2" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round" style="margin-top:7px;  vertical-align:bottom; padding-right: 5px;">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
            <path d="M11.795 21h-6.795a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v4" />
            <circle cx="18" cy="18" r="4" />
            <path d="M15 3v4" />
            <path d="M7 3v4" />
            <path d="M3 11h16" />
            <path d="M18 16.496v1.504l1 1" />
            <% str_fmt = "%s-%s-%s" %>
            <% str = pd.date.split("T")[0] %>
          </svg><%= "#{str_fmt % [str[8,2], str[5,2], str[0,4]]}, #{pd.date.split("T")[1]}" %></h5>
          <h5 class="card-text" style="margin-left: 12px; padding-right: 5px; color: black;"><iconify-icon icon="material-symbols:park" style="margin-right:5px;"></iconify-icon><%= "#{pd.location}" %></h5>
        </div>
        <div class="card-body col-3">

            <div class="card-link" style="position: absolute; right: 7px;top: 7px; color:black;"><iconify-icon icon="oi:question-mark" width="24"></iconify-icon></div>
            <%= link_to doggy_date_path(pd), data: {turbo_method: :delete} do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6" style="height:30px; position:absolute; right: 9px; bottom: 9px; color: black;">
                <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
              </svg>
            <% end %>
        </div>
      </div>
    </div>
  <%end%>
  <% @accepted_dates.each do |pd| %>
    <div class="card doggy" style="margin: 0 auto; margin-bottom:20px; border-radius: 20px; opacity: 0.9; box-shadow: 2px 1px 1px 1px black;">
      <div class="row">
        <div class="card-body col-9">
          <h5 class="card-title" style="margin-left: 12px;">
          <%if current_user.id == pd.match.matcher_id %>
            <iconify-icon icon="fa-solid:dog"></iconify-icon> <%= "#{pd.match.matchee.first_name}" %>
          <% else %>
            <iconify-icon icon="fa-solid:dog"></iconify-icon> <%= "#{pd.match.matcher.first_name}" %>
          <% end %></h5>
          <h5 class="card-subtitle mb-2" style="margin-left: 12px; color:black;">
            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-calendar-time" width="26" height="26" viewBox="0 0 24 24" stroke-width="1.2" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round" style="margin-top:7px;  vertical-align:bottom; padding-right: 5px;">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
            <path d="M11.795 21h-6.795a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v4" />
            <circle cx="18" cy="18" r="4" />
            <path d="M15 3v4" />
            <path d="M7 3v4" />
            <path d="M3 11h16" />
            <path d="M18 16.496v1.504l1 1" />
          </svg><%= "#{pd.date.split("T")[0]}, #{pd.date.split("T")[1]}" %></h5>
          <h5 class="card-text" style="margin-left: 12px; padding-right: 5px; color:black;"><iconify-icon icon="material-symbols:park" style="margin-right:5px;"></iconify-icon><%= "#{pd.location}" %></h5>
        </div>
        <div class="card-body col-3">

            <div class="card-link" style="position: absolute; right: 7px;top: 7px; color:black;"><iconify-icon icon="mdi:tick" width="32" height="32"></iconify-icon></div>
            <%= link_to doggy_date_path(pd), data: {turbo_method: :delete} do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6" style="height:30px; position:absolute; right: 9px; bottom: 9px; color: black;">
                <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
              </svg>
            <% end %>
        </div>
      </div>
    </div>
  <%end%>
</div>

app/views/doggy_dates/new.html.erb
<div class="container">
<h1>Book a doggy date!</h1>
  <%= simple_form_for [@match, @doggy_date] do |f| %>
    <%= f.datetime_field :date %>
    <%= f.input :location %>
      <div style="width: 100%; height: 600px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
      <div class="d-flex justify-content-center">
        <%= f.submit "Schedule your DoggyDate", class: "mt-4 btn btn-primary", style: "border-radius: 10px;" %>
      </div>
  <% end %>
</div>

app/views/doggy_dates/show.html.erb
<h1>DoggyDates#show</h1>
<p>Find me in app/views/doggy_dates/show.html.erb</p>