config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  get "/about-us", to: "pages#about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :dogs, only: [:create, :new, :edit, :update, :destroy]

  get "users/:id", to: "profiles#show", as: :show_profile

  resources :matches, only: [:update, :show] do
    collection do
      get :my_matches
    end


    resources :messages, only: :create
    resources :doggy_dates, exclude: [:index, :destroy]
  end

  resources :doggy_dates, only: [:index, :destroy]
  resources :notifications, only: [] do
    collection do
      patch :mark_as_read
    end
  end

  get "matches", to: "profiles#matches", as: :matches
  get "settings", to: "profiles#settings", as: :settings
  resources :matches, only: %i[update]
  post "matches", to: "matches#create", as: :create_match

  # TODO: nest doggy_dates index, new and create actions under matches

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZoomiesApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://code.iconify.design/iconify-icon/1.0.2/iconify-icon.min.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cabin:wght@700&family=Noto+Sans+JP:wght@500&display=swap" rel="stylesheet">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>
  </head>

  <body>
  <% if user_signed_in? %>
    <nav class="navbar navbar-expand-lg" style="background-color: #F0BB62;">
      <div class="container-fluid d-flex">
        <div class="justify-content-center">
          <%= link_to (about_us_path) do %>
          <%= image_tag "zoomies-thick.png", width:"150"%>
          <% end %>
        </div>
        <div class="flex-grow-1">
          <ul class="navbar-nav ms-auto d-flex flex-row justify-content-end align-items-center">
          <% if user_signed_in? %>
          <li class="nav-item fst-italic ps-2">
          Hi <%= current_user.first_name.split.first %>!
          </li>
          <% else %>
            <li class="nav-item ps-2">
              <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item ps-2">
              <%= link_to "Sign up", '/users/sign_up', class: "nav-link" %>
            </li>
          <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <% else %>

    <% end %>
    <p class="notice m-0"><%= notice %></p>
    <p class="alert m-0"><%= alert %></p>
    <%= render "shared/flashes" %>

    <%= yield %>
    <div class="py-5 my-3"> </div>
    <% if user_signed_in? %>
    <div class="container-fluid fixed-bottom px-0">
      <div class = "grass text-center justify-content-center flex-wrap" style ="">
      <%= image_tag("grass.png", width: "100%", height: "30px", crop: "fill") %>
      </div>
      <nav class="navbar navbar-expand-sm d-flex flex-wrap justify-content-center">
        <ul class="list-inline d-flex align-items-top mb-1">

            <li class="nav-item">
              <%= link_to show_profile_path(current_user.id), class: "nav-link" do %>
              <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user-circle" width="44" height="44" viewBox="0 0 24 24" stroke-width="1.2" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round" style="margin-top:7px;">
              <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
              <circle cx="12" cy="12" r="9" />
              <circle cx="12" cy="10" r="3" />
              <path d="M6.168 18.849a4 4 0 0 1 3.832 -2.849h4a4 4 0 0 1 3.834 2.855" />
              </svg>
              <% end %>
              </li>
            <li class="nav-item"  style="margin-top:7px;">
              <%= link_to matches_path, class: "nav-link" do %>
              <%= image_tag("noun-dog-house-3212489.svg", width: "56px") %>
              <% end %>
            </li>
            <li class="nav-item" id="matches-messages">
              <% if Notification.where({ recipient: current_user, read_at: nil }) != [] %>
                <%= link_to mark_as_read_notifications_path, class: "nav-link", data: {turbo_method: "PATCH"} do %>
                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-message-circle" width="44" height="44" viewBox="0 0 24 24" stroke-width="1.2" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round" style="margin-top:7px;">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                <path d="M3 20l1.3 -3.9a9 8 0 1 1 3.4 2.9l-4.7 1" />
                <line x1="12" y1="12" x2="12" y2="12.01" />
                <line x1="8" y1="12" x2="8" y2="12.01" />
                <line x1="16" y1="12" x2="16" y2="12.01" />
                </svg>
                <% end %>
                <%= image_tag("green-dot.png", width: "22px", id: "green-dot") %>
              <% else %>
                <%= link_to my_matches_matches_path, class: "nav-link" do %>
                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-message-circle" width="44" height="44" viewBox="0 0 24 24" stroke-width="1.2" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round" style="margin-top:7px;">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                <path d="M3 20l1.3 -3.9a9 8 0 1 1 3.4 2.9l-4.7 1" />
                <line x1="12" y1="12" x2="12" y2="12.01" />
                <line x1="8" y1="12" x2="8" y2="12.01" />
                <line x1="16" y1="12" x2="16" y2="12.01" />
                </svg>
                <% end %>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to doggy_dates_path, class: "nav-link" do %>
              <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-calendar-time" width="44" height="44" viewBox="0 0 24 24" stroke-width="1.2" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round" style="margin-top:7px;">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                <path d="M11.795 21h-6.795a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v4" />
                <circle cx="18" cy="18" r="4" />
                <path d="M15 3v4" />
                <path d="M7 3v4" />
                <path d="M3 11h16" />
                <path d="M18 16.496v1.504l1 1" />
              </svg>
              <% end %>
            </li>
          <% else %>
        </ul>
      </nav>
    </div>
    <% end %>
  </body>
</html>